### ISSUE TITLE
Cannot reproduce the nature

### ISSUE THREAD

**Issue by ayush020716** [jesperancinha/concert-demos-root#636]
Hi, I cannot use jmeter to connect to my spring webflux app, while when I clone your app and test it works. Can you please suggest what goes wrong? The source code for my reactive springboot app https://github.com/ayush020716/benchmarkReactive

**Comment by jesperancinha** [comment]
@ayush020716 , I see that your repo has been removed and I have had no time to have a look at it, hence the reason why I'm closing this issue. thank you any way for opening it.
